### ISSUE TITLE
Bug: viewBoxes missing

### ISSUE THREAD

**Issue by JoshuavanGelder** [Siteation/magento2-hyva-icons-lucide#52]
Hello,

I was updating this module and i realized all my viewBoxes were gone.

I see that that are no viewBoxes in the svg files. And i am getting issues because of that with icons smaller and bigger than the initial 
24 x 24

Example:
![image](https://github.com/user-attachments/assets/8216560a-4d62-44d9-a27c-8ce7354d5afb)

Is this something that can be fixed?

P.S. Dan sends his regards

Greetings,
Joshua van Gelder

**Comment by GrimLink** [comment]
I was made aware of this bug earlier but did not yet had time to fix it.
Sadly svgo still uses the removal of the viewbox in the default config, I have updated the config so it stays.

This is fixed in v2.1.1
